import styled from "styled-components";
export const Styled = { Wrapper: styled.footer`
    margin-top: 72px; border-top: 1px solid #1f1f1f; background: #070707;
    .footerInner { width: min(calc(100% - 48px), 1440px); margin: 0 auto; padding: 52px 0 24px; }
    .footerTop { display: grid; grid-template-columns: minmax(280px, .8fr) minmax(0, 1.2fr); gap: 70px; padding-bottom: 38px; }
    .brandBlock { max-width: 430px; } .brandHeading { display: flex; align-items: center; gap: 14px; } .brandHeading img { width: 46px; height: 46px; padding: 5px; border: 1px solid #303030; border-radius: 13px; background: #111; object-fit: contain; } .brandHeading > div { display: flex; flex-direction: column; gap: 4px; } .brandHeading strong { color: #f5f5f5; font-size: 1.25rem; } .brandHeading span { color: #5f5f5f; font-size: .625rem; font-weight: 800; letter-spacing: .11em; text-transform: uppercase; }
    .brandBlock > p { margin: 20px 0 0; color: #737373; font-size: .8125rem; line-height: 1.8; } .storageInfo { width: fit-content; margin-top: 20px; padding: 9px 11px; display: inline-flex; align-items: center; gap: 8px; border: 1px solid #252525; border-radius: 999px; color: #666; background: #0d0d0d; font-size: .625rem; font-weight: 700; } .statusDot { width: 6px; height: 6px; border-radius: 50%; background: #a3a3a3; box-shadow: 0 0 0 4px rgba(255,255,255,.035); }
    .footerLinks { display: grid; grid-template-columns: 1.2fr .8fr; gap: 42px; } .groupTitle { display: block; margin-bottom: 14px; color: #525252; font-size: .625rem; font-weight: 800; letter-spacing: .14em; text-align: right; text-transform: uppercase; } .iconLinks { display: flex; flex-wrap: wrap; justify-content: flex-end; gap: 8px; } .iconLinks a { display: inline-flex; width: 38px; height: 38px; align-items: center; justify-content: center; border: 1px solid #242424; border-radius: 11px; color: #737373; background: #0d0d0d; text-decoration: none; transition: color .18s ease, border-color .18s ease, box-shadow .18s ease, text-shadow .18s ease; } .iconLinks a:hover { color: #f5f5f5; border-color: #666; box-shadow: 0 0 14px rgba(255,255,255,.1); text-shadow: 0 0 10px rgba(255,255,255,.24); }
    .footerBottom { min-height: 66px; display: flex; align-items: center; justify-content: space-between; gap: 24px; border-top: 1px solid #1f1f1f; } .copyright { display: flex; align-items: center; flex-wrap: wrap; gap: 8px; color: #666; font-size: .6875rem; font-weight: 700; } .copyright a { color: #aaa; } .separator { color: #343434; } .backToTop { display: grid; width: 38px; height: 38px; place-items: center; border: 1px solid #292929; border-radius: 10px; color: #999; text-decoration: none; transition: border-color .18s ease, box-shadow .18s ease; } .backToTop:hover { border-color: #f5f5f5; box-shadow: 0 0 14px rgba(255,255,255,.1); }
    @media (max-width: 980px) { .footerTop { grid-template-columns: 1fr; gap: 42px; } .brandBlock { max-width: 600px; } } @media (max-width: 700px) { .footerInner { width: min(calc(100% - 28px), 1440px); padding-top: 40px; } .footerLinks { grid-template-columns: 1fr; gap: 24px; } .groupTitle, .iconLinks { justify-content: center; text-align: center; } } @media (max-width: 520px) { .footerBottom { padding: 20px 0; align-items: flex-start; flex-direction: column; } }
` }; 